#!/usr/bin/env bash
# vim:fileencoding=utf-8:foldmethod=marker

# Link to skhrc for <g-f>: ~/.config/skhd/skhdrc

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ensure that there are always 10 spaces
spacestocreate=10
spaces=$((spacestocreate - $(yabai -m query --spaces | jq length)))
while [ "$spaces" -gt 0 ]; do
	yabai -m space --create
	spaces=$((spaces - 1))
done

yabai -m config \
	mouse_follows_focus off \
	focus_follows_mouse off \
	mouse_modifier cmd \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap \
	window_origin_display default \
	window_placement second_child \
	window_border on \
	window_border_width 2 \
	window_shadow float \
	auto_balance on \
	layout bsp \
	window_gap 0 \
	window_animation_duration 0.1

APPS_ABOVE=(
	"JetBrains Toolbox"
	"Mullvad VPN"
	"Sip"
	"iStat Menus Status"
)
for app in "${APPS_ABOVE[@]}"; do
	yabai -m rule --add app="^$app\$" manage=off sticky=on layer=above border=off
done

APPS_UNMANAGED=(
	"GOG Galaxy"
	"Steam"
	"System Preferences"
)
for app in "${APPS_UNMANAGED[@]}"; do
	yabai -m rule --add app="^$app\$" manage=off
done

yabai \
	-m rule --add app="^CleanShot X\$" manage=off border=off \
	-m rule --add app="OBS Studio" manage=off sticky=on

echo "$(date -Iseconds): [RELOAD] finished loading yabai conf"
