# vim:ft=yaml:fenc=utf-8:fdm=marker
# zsh
.local/share/antigen/antigen.zsh:
  type: file
  url: "https://raw.githubusercontent.com/zsh-users/antigen/master/bin/antigen.zsh"
  refreshPeriod: 168h

# tmux plugin manager
.config/tmux/plugins/tpm:
  type: git-repo
  url: "https://github.com/tmux-plugins/tpm"
  refreshPeriod: 168h

# colorscheme stuff
.local/share/catppuccin/btop:
  type: git-repo
  url: "https://github.com/catppuccin/btop"
  refreshPeriod: 168h
