# vim:ft=yaml:fenc=utf-8:fdm=marker
# zsh
.local/share/antigen/antigen.zsh:
  type: file
  url: "https://raw.githubusercontent.com/zsh-users/antigen/master/bin/antigen.zsh"
  refreshPeriod: 168h

# neovim packer
.local/share/nvim/site/pack/packer/start/packer.nvim:
  type: git-repo
  url: "https://github.com/wbthomason/packer.nvim"
  refreshPeriod: 168h

# tmux plugin manager
.config/tmux/plugins/tpm:
  type: git-repo
  url: "https://github.com/tmux-plugins/tpm"
  refreshPeriod: 168h

# discocss
.local/bin/discocss:
  type: file
  url: "https://raw.githubusercontent.com/mlvzk/discocss/master/discocss"
  refreshPeriod: 168h

# colors
.config/qutebrowser/catppuccin:
  type: git-repo
  url: "https://github.com/catppuccin/qutebrowser.git"
  refreshPeriod: 168h
