[catppuccin-bat]
src.git = "https://github.com/catppuccin/bat"
fetch.github = "catppuccin/bat"

[milspec]
src.git = "https://github.com/nekowinston/milspec.nvim"
fetch.github = "nekowinston/milspec.nvim"

[nekowinston-wezterm-bar]
src.git = "https://github.com/nekowinston/wezterm-bar"
fetch.github = "nekowinston/wezterm-bar"

[yabai]
src.github = "koekeishiya/yabai"
fetch.url = "https://github.com/koekeishiya/yabai/releases/download/$ver/yabai-$ver.tar.gz"

[zsh-fast-syntax-highlighting]
src.git = "https://github.com/zdharma-continuum/fast-syntax-highlighting"
fetch.github = "zdharma-continuum/fast-syntax-highlighting"
