[milspec]
src.git = "https://github.com/nekowinston/milspec.nvim"
fetch.github = "nekowinston/milspec.nvim"

[nekowinston-wezterm-bar]
src.git = "https://github.com/nekowinston/wezterm-bar"
fetch.github = "nekowinston/wezterm-bar"

[zsh-fast-syntax-highlighting]
src.git = "https://github.com/zdharma-continuum/fast-syntax-highlighting"
fetch.github = "zdharma-continuum/fast-syntax-highlighting"
