on:
  push:
    paths:
    - "**.nix"
    - "**.lock"
  workflow_dispatch:

env:
  NIX_CONFIG: "accept-flake-config = true"

jobs:
  check:
    runs-on: "ubuntu-latest"

    steps:
    - uses: "https://github.com/actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4.2.2
    - uses: "https://github.com/DeterminateSystems/flake-checker-action@078f5f7f47ee188aa6cb472527ca5984e195222d" # v9
    - uses: "https://github.com/DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d" # v16
    - uses: "https://github.com/DeterminateSystems/magic-nix-cache-action@6221693898146dc97e38ad0e013488a16477a4c4" # v9

    - run: nix flake check --show-trace
