require("nvim-treesitter.configs").setup({
  auto_install = true,
  ignore_install = {
    -- woulnd't install sometimes, not needed
    "phpdoc",
  },
  highlight = {
    enable = true,
  },
  ensure_installed = {
    "bash",
    "css",
    "dockerfile",
    "go",
    "gomod",
    "graphql",
    "help",
    "hjson",
    "html",
    "http",
    "javascript",
    "jsdoc",
    "json",
    "json5",
    "jsonc",
    "latex",
    "lua",
    "make",
    "markdown",
    "php",
    "prisma",
    "python",
    "regex",
    "rust",
    "scss",
    "sql",
    "svelte",
    "teal",
    "toml",
    "tsx",
    "typescript",
    "vim",
    "yaml",
  },
})
