jobs:
  check:
    "runs-on": "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "DeterminateSystems/flake-checker-action@v5"
    - uses: "DeterminateSystems/nix-installer-action@v11"
    - uses: "DeterminateSystems/magic-nix-cache-action@v6"
    - env:
        NIX_CONFIG: |
          accept-flake-config = true
          extra-experimental-features = flakes nix-command
      run: "nix flake check --show-trace"
name: check
'on':
  push:
    paths:
    - "**.nix"
    - "**.lock"
