env:
  NIX_CONFIG: "accept-flake-config = true"
jobs:
  check:
    "runs-on": "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4.1.6"
    - uses: "DeterminateSystems/flake-checker-action@v8"
    - uses: "DeterminateSystems/nix-installer-action@v11"
    - uses: "DeterminateSystems/magic-nix-cache-action@v7"
    - run: "nix flake check --show-trace"
name: check
'on':
  push:
    paths:
    - "**.nix"
    - "**.lock"
